### ISSUE TITLE
Use desync to provide a cdn partial update

### ISSUE THREAD

**Issue by fire** [V-Sekai/world-godot#18]
https://github.com/folbricht/desync

Like 64 mb chunks that are stored on GitHub pages and mirrored on our website.

We keep the last major versions and all minor revisions for the current version.

Edited: 

64MB chunks are from the Riot Games blog https://technology.riotgames.com/news/supercharging-data-delivery-new-league-patcher

```bash
./desync-linux-amd64 tar -i -s archive/store --chunk-size 65536:65536:65536 archive/$dir.caidx other/$dir
```

https://github.com/V-Sekai/world-game-archived/blob/1f33cd301bce5db1cfe0ebec1ef04735c0634850/.github/workflows/package.yml

We could publish archives as release, but maybe a different minimum chunk size is wanted, assuming all the casync chunks are written once and never modified.

The main thing is that the URL schema needs to be in the same subdirectory as it already is.

1. https://github.com/V-Sekai/world-godot/releases/download/latest.v-sekai-editor-65/v-sekai-godot-android.zip
2. https://github.com/V-Sekai/world-godot/releases/download/latest.v-sekai-editor-65/v-sekai-godot-linuxbsd.zip

@dragonhunt02

**Comment by fire** [comment]
Can revisit later. The current system works well enough.

**Comment by dragonhunt02** [comment]
Split zips can cover web distribution for users. If we want to provide .catar archives without additional dependencies we need a js/wasm extractor or support from software like 7zip (they recently [implemented zstd support](https://github.com/ip7z/7zip/releases/tag/24.05) ).

**Comment by fire** [comment]
I have a wasm extractor via desync for the web.

**Comment by dragonhunt02** [comment]
Do you mean exporting that demo to web? Did you try it?
desync uses 'os' and 'syscall' I'm not sure it works.
